service: get-comments

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  apiGateway:
    restApiId:
      'Fn::ImportValue': MyApiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': MyApiGateway-rootResourceId
plugins:
  - serverless-plugin-typescript

functions:
  getComments:
    handler: handler.core
    events:
      - http:
          path: /waypoints/{waypointId}/comments
          method: post
          cors: true
    layers:
      - arn:aws:lambda:us-east-1:498397354579:layer:parseLayer